query GetAlerts ($responded: Boolean) {
    alerts(responded: $responded) {
        id
        createdAt
        room {
            name
        }
        responses {
            response
        }
        responded {
            response
        }
    }
}